#
# Cookbook Name:: linux-workstation
# Recipe:: apt
#
# TODO verify licence
# Copyright 2018, Contently
#
# All rights reserved - Do Not Redistribute
#
# Debugging - uncomment next two lines
# chef_gem 'pry'
# require 'pry'
#

#
# Force apt to keep your old configuration files when possible,
# instead of prompting for you to make a decision.
#

include_recipe 'apt'

file '/etc/apt/apt.conf.d/02dpkg-options' do
  mode 0444
  content <<-EOM.gsub(/^ {4}/,'')
    Dpkg::Options {
      "--force-confdef";
      "--force-confold";
    }
  EOM
end

release_codename = node[:lsb][:codename]

file '/etc/apt/sources.list' do
  mode 0644
  content <<-EOM
# Generated by Chef

deb      [arch=amd64] "http://mirror.cc.columbia.edu/debian" #{release_codename} main contrib non-free
deb-src  [arch=amd64] "http://mirror.cc.columbia.edu/debian" #{release_codename} main contrib non-free
  EOM
end

apt_repository 'security' do
  arch 'amd64'
  uri 'http://security.debian.org/debian-security'
  distribution "#{release_codename}/updates"
  components %w(main)
  deb_src node['debian']['deb_src']
end

apt_repository 'backports' do
  arch 'amd64'
  uri node['debian']['mirror']
  distribution "#{release_codename}-backports"
  components %w(main contrib non-free)
  deb_src node['debian']['deb_src']
end

apt_preference "#{release_codename}-stable" do
  glob '*'
  pin "release n=#{release_codename}"
  pin_priority '600'
  notifies :run, 'execute[apt-get update]', :immediately
end

apt_preference "#{release_codename}-backports" do
  glob '*'
  pin "release n=#{release_codename}-backports"
  pin_priority '500'
  notifies :run, 'execute[apt-get update]', :immediately
end

# apt_preference "#{release_codename}-security" do
#   glob '*'
#   pin "release n=#{release_codename}-backports"
#   pin_priority '500'
#   notifies :run, 'execute[apt-get update]', :immediately
# end

package %w(apt-transport-https gnupg dirmngr debian-archive-keyring curl) do
  action :upgrade
end
