---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  product_name: chef
  product_version: 14.12.3

verifier:
  name: inspec

platforms:
  - name: debian-9

suites:
  - name: linux-workstation-default
    run_list:
      - recipe[linux-workstation::default]
    verifier:
      inspec_tests:
        - test/apt
        - test/nvidia
    attributes:
      desktop:
        user:
          uid: 1001
          gid: 1001
