---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-10

suites:
  - name: linux-workstation-default
    run_list:
      - recipe[linux-workstation::default]
    verifier:
      inspec_tests:
        - test/apt
        - test/nvidia
    attributes:
      desktop:
        user:
          uid: 1001
          gid: 1001
